### PR TITLE
4102: Change default Slack App Icon

### PR DESCRIPTION
**Pull request by WilliamBergamin**
### Type of change

- [ ] New sample
- [ ] New feature
- [x] Bug fix
- [ ] Documentation

### Summary

This resolves issue 4102

Currently our templates ship Deno image to use as an icon. We should change this to a Slacky image in all of our templates. 

I've reached out to Product Design they recommend using default app image for this. This PR implements this.

### Requirements

- [x] I’ve checked my submission against the Samples Checklist to ensure it complies with all standards
- [x] I have ensured the changes I am contributing align with existing patterns and have tested and linted my code
- [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct)

### CODE REVIEW

**Review by filmaj — CHANGES_REQUESTED** [review]
I much prefer the old icon, so I don't want this 🙅

**Comment by WilliamBergamin** [comment]
I talked to the Product Design they informed me we should be using this image for our sample apps. I think this is a bit boring.

We can't use the Deno image from before for this , but if you have some graphic design skills maybe we can make something work by making a variant of the slack default image (easter egg type thing)

**Review by srajiang — APPROVED** [review]
Is a tie breaker needed here? We've already merged one of these changes (approved) in another sample, and I think we ought to to opt for consistency at this point. 

I agree - it's not that pretty, but something to revisit in the future since the main goal of this work was to move away from the Deno logo, which we've done here. 

LGTM!

**Comment by WilliamBergamin** [comment]
@srajiang @filmaj I think we can always go back and change the image, we just need someone with photo editing skills to make something we can all agree on

**Pull request merged**
